### ISSUE TITLE
Algorithm doesnt consider mask properly

### ISSUE THREAD

**Issue by kartikwar** [esimov/caire#86]
I was playing around with the mask parameter and I feel that the algorithm sometimes distorts the masked objects. For example in this image I marked the girl as important, still in output her face was not preserved. Is there any parameter where I can force the algorithm to not touch the masked object (like completely ignore it)

![example](https://user-images.githubusercontent.com/17046431/195509935-672aef1f-804e-48b6-bfd1-44c31feff5e8.jpg)
![sal_example](https://user-images.githubusercontent.com/17046431/195509942-47f54b97-2a17-4008-9c39-d3c0533e94f3.png)
![output](https://user-images.githubusercontent.com/17046431/195509951-fa36b896-dca7-474c-8ee5-e3948593cbc4.jpg)

**Comment by esimov** [comment]
What I can see at a first sight is that the source image and the mask image has two different size. The mask image should have exactly the same size as the source image to work properly. The logic behind is identical with the face detection: I'm just making some XOR operations with the image mask and the sobel operator, in other words the zones which have more white patches are not altered by the seam carver.

**Comment by kartikwar** [comment]
Sorry I had uploaded the wrong image. This is the correct mask image I had used 
![sal_example](https://user-images.githubusercontent.com/17046431/195526565-644f88de-781b-44c9-81bb-4a9b810210f1.jpg)
The output is same as before

**Comment by esimov** [comment]
Looks like that for vertical resizing something is not working quite well. For horizontal resize this is what I got using the following command:

```bash
$ caire -in testdata/sample.jpg -out output.jpg -perc=1 -width=50 -mask "mask.jpg" -debug=1
```

![output](https://user-images.githubusercontent.com/883386/195531603-5afc331e-5020-4f2b-b6cb-18b57c914d72.jpg)

**Comment by kartikwar** [comment]
This is decent output. Is there any workaround to make it work for vertical resizing as well?

**Comment by esimov** [comment]
I'll have to debug it. Sure it should work both for horizontal and vertical resizing equally.

**Comment by kartikwar** [comment]
Thank you @esimov.

**Comment by esimov** [comment]
This issue should be fixed now. You should pull out the new code changes. Let me know if it's working for you.

**Comment by kartikwar** [comment]
I tried the latest code. There still seems to be some distortion in the face . Also the algorithm is still not considering the background leaves as the pixels for carving out. 

go run main.go  -in example.jpg -out output.jpg   -width=500 -height=300 -mask sal_example.jpg 

![output_latest](https://user-images.githubusercontent.com/17046431/196119601-60cf2787-72ac-4d31-9421-a82ec9d29d90.jpg)


go run main.go  -in example.jpg --perc=1 -out output.jpg    -height=10 -width=50 -mask sal_example.jpg 

![output_height_10_width_50](https://user-images.githubusercontent.com/17046431/196120044-fcdd713c-07e5-4074-be1e-bb58fa939bfe.jpg)

**Comment by esimov** [comment]
I can confirm that the last example is not working as expected. I will check it soon.

**Comment by kartikwar** [comment]
Thank you @esimov. Will  look forward to the solution

**Comment by kartikwar** [comment]
I closed this by mistake. Reopening it

**Comment by esimov** [comment]
Now it should work also when percentage is used. Right now I'm working on some updates to facilitate the GUI debugging. Once it's done and the GUI debug mode is enabled it will be much easier for everyone to get a real sense how the algorithm is working.

**Comment by esimov** [comment]
If you don't have any objections I would close this ticket.

**Comment by esimov** [comment]
Since I didn't get any response I will close this ticket.
